# Generated by Django 4.2 on 2023-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.CharField(max_length=10, null=True, verbose_name='Edad'),
        ),
    ]
