# Generated by Django 4.2 on 2023-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre'),
        ),
    ]
