# Generated by Django 4.2 on 2023-04-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumnos_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alumnos',
            new_name='Alumno',
        ),
    ]
