# Generated by Django 4.2 on 2023-05-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
