# Generated by Django 4.2 on 2023-05-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
