# Generated by Django 4.2 on 2023-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='lugar',
            field=models.CharField(max_length=10000, null=True, verbose_name='Lugar'),
        ),
    ]
